### ISSUE TITLE
swoole_http_response::end(): Http request is end.

### ISSUE THREAD

**Issue by Frewen** [myqee/server#2]
server/src/WorkerAPI.php中第53行

`$response->end('{"status":"error","code":0,"msg":"verify fail."}');`

会导致错误，后续代码无法正常结束

> PHP Warning:  swoole_http_response::end(): Http request is end. in /home/vagrant/Code/swoole/server/vendor/myqee/server/src/WorkerAPI.php on line 87
> PHP Stack trace:
> PHP   1. {main}() /home/vagrant/Code/swoole/server/server:0
> PHP   2. MyQEE\Server\Server->start() /home/vagrant/Code/swoole/server/server:9
> PHP   3. MyQEE\Server\Server->startWorkerServer() /home/vagrant/Code/swoole/server/vendor/myqee/server/src/Server.php:244
> PHP   4. swoole_http_server->start() /home/vagrant/Code/swoole/server/vendor/myqee/server/src/Server.php:344
> PHP   5. MyQEE\Server\Server->onRequest() /home/vagrant/Code/swoole/server/vendor/myqee/server/src/Server.php:344
> PHP   6. MyQEE\Server\WorkerAPI->onRequest() /home/vagrant/Code/swoole/server/vendor/myqee/server/src/Server.php:659
> PHP   7. swoole_http_response->end() /home/vagrant/Code/swoole/server/vendor/myqee/server/src/WorkerAPI.php:87

swoole官网文档描述：
- end操作后将向客户端浏览器发送HTML内容，并销毁$request/$response对象
- 如果开启了KeepAlive，连接将会保持，服务器会等待下一次请求
- 未开启KeepAlive，服务器将会切断连接

**Comment by breath-co2** [comment]
谢谢反馈，这个api对象的 onRequest() 事件是不需要自己去 $response->end() 的，否则会和系统默认的 end 冲突，如果想自己去输出，可以覆盖 WorkerAPI 的 onRequest 的方法的
