### ISSUE TITLE
这个yaml扩展真难安装啊.....解析

### ISSUE THREAD

**Issue by luciferid** [myqee/server#4]
(1)能不能把配置文件改成数组 加注释的模式.........
(2)能不能提供一个yaml的安装流程php7上.......

**Comment by loyating** [comment]
php7 安装yaml扩展
pecl install yaml-2.0.0

**Comment by breath-co2** [comment]
稍后我改下，如果没有这个扩展就用php来解析 yaml

**Comment by breath-co2** [comment]
使用master 分支可以支持 `symfony/yaml` 的php解析方法，使用方法：
在项目根目录用 `composer require symfony/yaml` 命令来安装即可
