### ISSUE TITLE
后面的一个启动的TCP服务调用sendMessage,前面一个TCP服务接收不到消息？

### ISSUE THREAD

**Issue by ctrl-cli** [myqee/server#6]
您好：

后面的一个启动的TCP服务调用sendMessage,前面一个TCP服务接收不到消息？

![qq 20170519183604](https://cloud.githubusercontent.com/assets/13032442/26244717/8846159c-3cc3-11e7-941c-b78bcd026b3c.png)

**Comment by breath-co2** [comment]
这个设计的在 Main 里发的只在 Main 类里收到，在 Nlp 里发的只在 Nlp 里收到，稍后我确认下

**Comment by ctrl-cli** [comment]
@breath-co2 嗯嗯 谢谢 我改了调用Message消息对象,这个效果还蛮好的。

我在一个worker类里面onStart的时候初始化了一个redis连接

我是在task类里面调用message对象,

然后worker类里面的$server有些时候报找不到$server->redis
`public static function getMessage($server, $fromWorkerId, $obj, $fromServerId)`

**Comment by breath-co2** [comment]
@gobyang 你之前反应的 Message 的问题已经修复了，使用 1.0.6 版本或 master 分支即可。。

然后你提到的 redis 的问题，在 worker 里启动的 redis 只在当前 worker 进程，在 task 进程是不存在的，所以需要在 task 里也初始化一个。。（ps: 不要在 start 前初始化 redis、mysql 这些连接，在每个进程里单独初始化是推荐的做法）
